version: 2

updates:

- package-ecosystem: "gomod"
  directory: "/"
  schedule:
    interval: "weekly"
  ignore:
    - dependency-name: "*"
      update-types: ["version-update:semver-major"]

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
  ignore:
    - dependency-name: "*"
      update-types: ["version-update:semver-major"]
