name: main

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
    paths-ignore:
      - '**/*.md'
      - '**/.gitignore'
  pull_request:
    paths-ignore:
      - '**/*.md'
      - '**/.gitignore'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:  ["windows-latest", "ubuntu-latest", "macOS-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Install dependencies
        run: go get .
      - name: Build
        run: go build -v ./...
      - name: Test with the Go CLI
        run: go test -v ./... -shuffle=on -timeout=3m -cover
